# Generated by Django 3.1.2 on 2020-10-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcasts',
            name='artist',
            field=models.TextField(null=True),
        ),
    ]
