# Generated by Django 3.1.2 on 2020-10-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_podcasts_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcasts',
            name='artist',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
