# Generated by Django 3.1.2 on 2020-10-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Enterprise', 'ent'), ('Standard', 'std'), ('Basic', 'bsc')], default='Enterprise', max_length=30),
        ),
    ]
